
name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up .NET Core'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: 'Restore dependencies'
      run: dotnet restore ./POCApp/POCApp.csproj

    - name: 'Build'
      run: dotnet build --configuration Release ./POCApp/POCApp.csproj

    - name: 'Publish'
      run: dotnet publish --configuration Release --output ./POCApp/publish ./POCApp/POCApp.csproj

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-azure-app-name'  # Replace with your Azure app name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./POCApp/publish
